<?php

$title = 'Delete term';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($term->abbreviation); ?></h1>

<p>Are you sure that you want to delete
  '<?php echo $this->escapeHtml($term->abbreviation); ?>' (
  '<?php echo $this->escapeHtml($term->standsfor); ?>')?
</p>
<?php
$url = $this->url('term', array(
  'action' => 'delete',
  'id' => $this->id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
  <div>
    <input type="hidden" name="id" value="<?php echo (int) $term->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
  </div>
</form>